var _0 = [
];
var _1 = [
		"001.mp3",
		"002.mp3",
		"003.mp3",
		"004.mp3",
		"005.mp3",
		"006.mp3",
		"007.mp3",
		"008.mp3",
		"009.mp3",
		"010.mp3",
		"011.mp3",
		"012.mp3",
		"013.mp3",
		"014.mp3",
		"015.mp3",
		"016.mp3",
		"017.mp3",
		"018.mp3",
		"019.mp3",
		"020.mp3",
		"021.mp3",
		"022.mp3",
		"023.mp3",
		"024.mp3",
		"025.mp3",
		"026.mp3",
		"027.mp3",
		"028.mp3",
		"029.mp3",
		"030.mp3",
		"031.mp3",
		"032.mp3",
		"033.mp3",
		"034.mp3",
		"035.mp3",
		"036.mp3",
		"037.mp3",
		"038.mp3",
		"039.mp3",
];
var _2 = [
		"25 Minutes - Michael Learns To Rock.mp3",
		"A little love - Fiona Fung.mp3",
		"All That I Need - Boyzone.mp3",
		"Amazed (AC Mix) - Lonestar.mp3",
		"Angel - Sarha Mclachlan.mp3",
		"Angel Of Mine - Eternal.mp3",
		"Anyone of us - Gareth Gates.mp3",
		"Apologize - OneRepublic.mp3",
		"As Long As You Love Me - BackStreet Boys.mp3",
		"Bad Day - Daniel Powter.mp3",
		"Barbie Girl - AQua.mp3",
		"Beautiful In White - Shane Filan.mp3",
		"Beautiful life - Ace Of Base.mp3",
		"Beautiful Sunday - Daniel Boone.mp3",
		"Because I Love you - Shakin Stevens.mp3",
		"Because You Love Me - Celine Dion.mp3",
		"Big Big World - Emilia.mp3",
		"Boom Boom Boom - Vengaboys.mp3",
		"Boulevard - Dan Byrd.mp3",
		"Breathe - Faith Hill.mp3",
		"Breathless - Shayne Ward.mp3",
		"Bring Me Down.mp3",
		"Broken Hearted Girl.mp3",
		"Butterfly Kisses - Westlife.mp3",
		"By my side - Dang cap nhat.mp3",
		"Can you feel the love tonight - Elton John.mp3",
		"Caravan of life - Tokyo Square.mp3",
		"Careless Whisper - George Michael.mp3",
		"Casablanca - Bertie Higgins.mp3",
		"Cherish - Kool & The Gang.mp3",
		"Child - Little Fox.mp3",
		"Circle in The Sand - Belinda Carlisle.mp3",
		"Circus.mp3",
		"Color of the night - Lauren Christy.mp3",
		"Color of the Wind - Vanessa Williams.mp3",
		"Come Back To Me.mp3",
		"Crazier.mp3",
		"Crush.mp3",
		"Cry On My Shoulder - Super Stars.mp3",
		"Crying In The Rain.mp3",
		"Delilah - Tom Jones.mp3",
		"Don't Be Stupid - Shania Twain.mp3",
		"Don't cry for me Argentina (1977) - Julie Covington.mp3",
		"Don't cry Joni.mp3",
		"Don't Let Me Fail.mp3",
		"Dragon Fly.mp3",
		"Earth Song - micheal jackson.mp3",
		"Endless Love - Diana Ross - Lionel Richie.mp3",
		"Eternal Flame - Dang cap nhat.mp3",
		"Every Breath You Take - The Police.mp3",
		"Every moment of my life - Sarah Connor.mp3",
		"Every Part Of Me.mp3",
		"Everybody - BackStreet Boys.mp3",
		"Everyday I Love You - Boyzone.mp3",
		"Everything I do, I do it for you - Bryan Adams.mp3",
		"Everytime - A1.mp3",
		"Everytime - Britney Spears.mp3",
		"Everytime You Go Away - Paul Young.mp3",
		"Foolish Beat - Debbie Gibson.mp3",
		"Forever Friend - Fiona Fung.mp3",
		"Forever Love - Gary Barlow.mp3",
		"Frozen - Madonna.mp3",
		"Get Down - BackStreet Boys.mp3",
		"Girl Of My Dreams - The Moffatts.mp3",
		"Girl you are my love - Pink Boy.mp3",
		"Goodbye.mp3",
		"Happy new year - ABBA.mp3",
		"Hard To Say I'm Sorry - Chicago.mp3",
		"Have I Told You Lately - Rod Steward.mp3",
		"Heal the world - Michael Jackson.mp3",
		"Hero - Mariah Carey.mp3",
		"Hold Me For A While - Rednex.mp3",
		"Home - Michael Buble.mp3",
		"Hot and cold.mp3",
		"How Can I Tell Her - Lobo.mp3",
		"How Did I Fall In Love With You - BackStreet Boys.mp3",
		"I cry - Yuri Chika.mp3",
		"I Just Called To Say I Love You - Stevie Wonder.mp3",
		"I knew I love you  - Savage Garden.mp3",
		"I Lay My Love On You - Westlife.mp3",
		"I Like Chopin - Gazebo.mp3",
		"I love the way you love me - Boyzone.mp3",
		"I Love You - Celine Dion.mp3",
		"I m Not A Girl Not Yet A Woman.mp3",
		"I Need You - Westlife.mp3",
		"I Swear - All 4 One.mp3",
		"I Told You So.mp3",
		"I Wanna Know You.mp3",
		"I Want It That Way - Backstreet Boys.mp3",
		"I Will Always Love You - Whitney Houston.mp3",
		"I Will Follow Him - Sandy Posey.mp3",
		"I'm Your - Jason Mraz.mp3",
		"If - Bread.mp3",
		"If we hold on together - Diana Ross.mp3",
		"If you had my love - Jennifer Lopez.mp3",
		"Jai Ho You Are My Destiny.mp3",
		"Jamaica Farewell - Carly Simon.mp3",
		"Jingle Bells - Alan Jackson.mp3",
		"Killing me softly - Eva Cassidy.mp3",
		"Kiss - Vengaboys.mp3",
		"Knife - Rockwell.mp3",
		"Knock Knock.mp3",
		"Knock Three Times - Dawn.mp3",
		"Last Christmas - Taylor Swift.mp3",
		"Lemon Tree - Fool's Garden.mp3",
		"Let s Get Crazy.mp3",
		"Lipstick On Your Collar - Connie Francis.mp3",
		"Lost In Love - Air Supply.mp3",
		"Love Is Blue - Dusty Springfield.mp3",
		"Love Paradise.mp3",
		"Love Story - Taylor Swift.mp3",
		"Love to be loved by you - MarcTerenzi.mp3",
		"Lover's concerto - Kelly Chen.mp3",
		"Making Love Out Of Nothingat All - Air Supply.mp3",
		"Marry You - Bruno Mars.mp3",
		"Mary's song (Oh my my my) - Taylor Swift.mp3",
		"Midnight Lady - Chris Norman.mp3",
		"Miss you - Westlife.mp3",
		"Mistletoe - Justin Bieber.mp3",
		"More than I can say - Leo Sayer.mp3",
		"My heart will go on - Celine Dion.mp3",
		"My Love - Westlife.mp3",
		"My Valentine - Martina Mcbride.mp3",
		"No matter what.mp3",
		"No Promises - Shayne Ward.mp3",
		"Oh Carol - Dang cap nhat.mp3",
		"Only love - Trademark.mp3",
		"Over and over - Nana Mouskouri.mp3",
		"Papa - Paul Anka.mp3",
		"Pretty Boy - M2M.mp3",
		"Proud of you.mp3",
		"Quando Quando Quando - Engelbert Humperdinck.mp3",
		"Rhythm of the rain - Cascades.mp3",
		"Right here waiting for you - Richard Marx.mp3",
		"Sacrifice - Elton John.mp3",
		"Sailing - Rod stewart.mp3",
		"Santa Claus Is Coming To Town - Faith Hill.mp3",
		"Save The Best For Last - Vanessa Williams.mp3",
		"Saving All My Love For You - Whitney Houston.mp3",
		"Say you say me - Lionel Richie.mp3",
		"Say you will - Tokyo Square.mp3",
		"Sayonara.mp3",
		"Sealed with a kiss - Brian Hyland.mp3",
		"Season in the sun - Westlife.mp3",
		"Self Control - Laura Branigan.mp3",
		"Shining Friends -  Fiona Fung.mp3",
		"Show Me The Meaning Of Being Lonely - BackStreet Boys.mp3",
		"Sleeping Child - Michael Learns To Rock.mp3",
		"Slow dancing with the moon.mp3",
		"Soledad - Westlife.mp3",
		"Something about you look away - Elton John.mp3",
		"Sometimes when we touch - Dan Hill.mp3",
		"Sorry Seems.mp3",
		"Stand.mp3",
		"Summer kisses winter tears - Elvis.mp3",
		"Sunny - Boney M.mp3",
		"Take Me To Your Heart - Michael Learns To Rock.mp3",
		"Teardrops on my guitar (Sad song) - Taylor Swift.mp3",
		"That is love - Toryo Souare.mp3",
		"That's Why .mp3",
		"The Climb - Miley Cyrus.mp3",
		"The color of the night - Laurent Christy.mp3",
		"The day you went away.mp3",
		"The earth song - Michael.mp3",
		"The mouse loves the rice.mp3",
		"The Sailor Song - ToyBox.mp3",
		"The Show - Lenka.mp3",
		"This I Promise You - NSync.mp3",
		"Tonight I Celebrate My Love For You - Peabo Bryson & Roberta Flack.mp3",
		"Top of the world - The Carpenters.mp3",
		"True Color -  Fiona Fung.mp3",
		"Unbreak My Heart - Toni Braxton.mp3",
		"Until You - Shayne Ward.mp3",
		"Vulnerable.mp3",
		"Way back into love - Hugh Grant.mp3",
		"We Wish You A Merry Christmas - Enya.mp3",
		"What is love - Haddawa.mp3",
		"When I Grow Up.mp3",
		"Within you'll Remain.mp3",
		"Woman In Love - Barbra Streisand.mp3",
		"Womanizer - Britney Spears.mp3",
		"You Are Not Alone - Michael Jackson.mp3",
		"You Belong With Me.mp3",
		"You Raise Me Up - Westlife.mp3",
		"You're Beautiful - James Blunt.mp3",
		"You're my everything - Santa Esmeralda.mp3",
		"You've Got a Way - Shania Twain.mp3",
		"Your Love - Dang cap nhat.mp3",
		"Youre My Heart, Youre My Soul - Modern Talking.mp3",
];
var _3 = [
		"Androcles and the Lion.mp3",
		"Chicken Little.mp3",
		"Don’t Be Scared of Halloween NEW VERSION.mp3",
		"How the Tiger Got his Stripes.mp3",
		"Jack and the Pirate School Part 1.mp3",
		"Life is a Circus.mp3",
		"The Boy Who Cried Wolf.mp3",
		"The First Strawberries.mp3",
		"The Grateful Crane.mp3",
		"The Old Man and the Figs.mp3",
];
var _4 = [
		"ListeningPracticeThroughDictation_1-01.mp3",
		"ListeningPracticeThroughDictation_1-02.mp3",
		"ListeningPracticeThroughDictation_1-03.mp3",
		"ListeningPracticeThroughDictation_1-04.mp3",
		"ListeningPracticeThroughDictation_1-05.mp3",
		"ListeningPracticeThroughDictation_1-06.mp3",
		"ListeningPracticeThroughDictation_1-07.mp3",
		"ListeningPracticeThroughDictation_1-08.mp3",
		"ListeningPracticeThroughDictation_1-09.mp3",
		"ListeningPracticeThroughDictation_1-10.mp3",
		"ListeningPracticeThroughDictation_1-11.mp3",
		"ListeningPracticeThroughDictation_1-12.mp3",
		"ListeningPracticeThroughDictation_1-13.mp3",
		"ListeningPracticeThroughDictation_1-14.mp3",
		"ListeningPracticeThroughDictation_1-15.mp3",
		"ListeningPracticeThroughDictation_1-16.mp3",
		"ListeningPracticeThroughDictation_1-17.mp3",
		"ListeningPracticeThroughDictation_1-18.mp3",
		"ListeningPracticeThroughDictation_1-19.mp3",
		"ListeningPracticeThroughDictation_1-20.mp3",
		"ListeningPracticeThroughDictation_1-21.mp3",
		"ListeningPracticeThroughDictation_1-22.mp3",
		"ListeningPracticeThroughDictation_1-23.mp3",
		"ListeningPracticeThroughDictation_1-24.mp3",
		"ListeningPracticeThroughDictation_1-25.mp3",
		"ListeningPracticeThroughDictation_1-26.mp3",
		"ListeningPracticeThroughDictation_1-27.mp3",
		"ListeningPracticeThroughDictation_1-28.mp3",
		"ListeningPracticeThroughDictation_1-29.mp3",
		"ListeningPracticeThroughDictation_1-30.mp3",
		"ListeningPracticeThroughDictation_1-31.mp3",
		"ListeningPracticeThroughDictation_1-32.mp3",
		"ListeningPracticeThroughDictation_1-33.mp3",
		"ListeningPracticeThroughDictation_1-34.mp3",
		"ListeningPracticeThroughDictation_1-35.mp3",
		"ListeningPracticeThroughDictation_1-36.mp3",
		"ListeningPracticeThroughDictation_1-37.mp3",
		"ListeningPracticeThroughDictation_1-38.mp3",
		"ListeningPracticeThroughDictation_1-39.mp3",
		"ListeningPracticeThroughDictation_1-40.mp3",
];
var _5 = [
];
var _6 = [
		"Beautiful In White_Shane Filan_-1074123500.mp3",
		"I Do_911_-1074710306.mp3",
		"Lạc Nhau Có Phải Muôn Đời (Movie Version)_ERIK ST.319_-1075806325.mp3",
		"Mặt Trời Của Em_Phương Ly, JustaTee_-1076420203.mp3",
		"Người Em Tìm Kiếm_MIN_-1076380391.mp3",
		"Người Lạ Ơi_Karik, Orange, Superbrothers_-1078016588.mp3",
		"Xinh Tươi Việt Nam (Acoustic Version)_V.Music_-1073866342.mp3",
		"y2mate.com - cong_chua_bong_bong_team_bao_thy_ft_quang_vinh_tap_5_minishow_combat_remix_new_generation_2017_IYyidFOBLis.mp3",
		"Yêu Em Rất Nhiều_Hoàng Tôn_-1076377293.mp3",
		"Yêu Đi Đừng Sợ (OST Yêu Đi Đừng Sợ)_OnlyC_-1076351780.mp3",
		"ĐỪNG HỎI EM (DON'T ASK ME) - MỸ TÂM (Audio).mp3",
];
var _7 = [
];
var _8 = [
		"A Gift of Clear Vision in Developing Countries.mp3",
		"Applicants Ask Colleges- Why Should I Accept You-.mp3",
		"Behind the Price of Rice.mp3",
		"Bill Gates Steps Aside at Microsoft.mp3",
		"Book Predicts Jump in High School Courses Online.mp3",
		"Cooking Meals With the Sun.mp3",
		"Data Centers Power a Big Change in Computing.mp3",
		"Debating Eighth-Grade Graduations.mp3",
		"Ear Care- Do-It-Yourself Wax Removal.mp3",
		"Farming Techniques That Will Feed a Family.mp3",
		"Fighting Music Piracy on College Campuses.mp3",
		"Fighting Witchweed in African Sorghum.mp3",
		"For Fans of Anarchy, Grand Theft Auto IV Is a Big Smash.mp3",
		"For High Definition TVs, Blu-ray Gets a Big Supporter.mp3",
		"Foreign Student Series- College, University or Institute-.mp3",
		"Foreign Student Series- First Steps.mp3",
		"Getting Weather Reports to Rural Communities.mp3",
		"Got Milk- Why Not Bank It.mp3",
		"High Fuel Prices Mean a Hard Road for School Buses.mp3",
		"Joseph Juran, 1904-2008- A Life of Quality Control.mp3",
		"Minding the Summer Learning Gap.mp3",
		"Need Your Appendix Out- Let Me Reach Down Your Throat.mp3",
		"Online Learning Grows, but Research Finds Mixed Results.mp3",
		"Peter Drucker, 1909-2005- The Mind of a Management Thinker.mp3",
		"Teenagers and Pregnancy.mp3",
		"Understanding Down Syndrome.mp3",
		"Using Personal Computers to Solve Humanitarian Problems.mp3",
		"When a Stroke Is Silent.mp3",
		"Why Oil Continues Its Climb.mp3",
		"World Economic Growth Expected to Slow in '08.mp3",
];
var listCollection = {
		"_1": new CollectionItem("D:/DATA/MEDIA/1-Vocab-nn24h", _1, "1-Vocab-nn24h"),
		"_2": new CollectionItem("D:/DATA/MEDIA/English Song_Audio", _2, "English Song_Audio"),
		"_3": new CollectionItem("D:/DATA/MEDIA/EnglishStory_Audio", _3, "EnglishStory_Audio"),
		"_4": new CollectionItem("D:/DATA/MEDIA/ListeningPracticeThroughDictation_1", _4, "ListeningPracticeThroughDictation_1"),
		"_6": new CollectionItem("D:/DATA/MEDIA/music", _6, "music"),
		"_8": new CollectionItem("D:/DATA/MEDIA/VOA_Audio", _8, "VOA_Audio"),
};
